# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4abb81d560e82c553e1c092af976178e8b24d278b240e4bcb55500420bf6303802a7667ee4bcb6c7297edd8a3493fa902f1c39e347e94bf67ddd3ccdc86ae41

test:
  secret_key_base: 592755158dd5f21b930c8e978f37bef7ce7c96aeaa77c48ac5400fb5a66b9a1ff4c492aa3a2a5094aa68a5a1cf676ae40f402b842098b8c051237e7a7e2db37a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
